name: Deploy Blazor WASM to GitHub Page
env:
  PUBLISH_DIR: bin/Release/net6.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0

    - name: Publish application
      run: dotnet publish -c Release -o release --nologo
      
   #changes the base-tag in index.html from '/' to 'PrismLuxe' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to PrismLuxe
      run: sed -i 's/<base href="\/" \/>/<base href="\/PrismLuxe\/" \/>/g' release/wwwroot/index.html
        
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch ${{ env.PUBLISH_DIR }}/.nojekyll

    - name: Commit to GitHub pages Repo
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
       #fqdn: www.eptx-al-anon.com
        target_branch: gh-pages
        build_dir: ${{ env.PUBLISH_DIR }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
